import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, Asterisk, BookOpen, Box, ChevronRight, CircuitBoard, Cpu, GitBranch as Github, Menu, Microscope, MonitorCog, MoveUpRight, Ruler, Search, Send, ShieldCheck, Sparkles, Terminal, X } from 'lucide-react'
import { navItems, projects, researchTopics, skillGroups, toolbox, type Project } from './data/content'
import './App.css'

const iconMap = [Cpu, Ruler, Terminal, Sparkles, MonitorCog, CircuitBoard, Microscope, Github]

function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: React.ReactNode; text?: string }) {
  const [number, label] = eyebrow.split(' / ')
  return <motion.div className="section-heading" initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .25 }} transition={{ duration: .55 }}><span className="eyebrow"><span className="section-number">{number}</span><span>{label || eyebrow}</span></span><h2>{title}</h2>{text && <p>{text}</p>}</motion.div>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  useEffect(() => { const handleScroll = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', handleScroll); return () => window.removeEventListener('scroll', handleScroll) }, [])
  useEffect(() => { document.body.style.overflow = selectedProject || menuOpen ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [selectedProject, menuOpen])
  const closeMenu = () => setMenuOpen(false)

  return <div className="site-shell">
    <header className={`navbar ${scrolled ? 'navbar-scrolled' : ''}`}>
      <a className="wordmark" href="#home" onClick={closeMenu} aria-label="Manish Pal home"><span className="wordmark-mark">MP</span><span>MANISH PAL <small>/ ECE</small></span></a>
      <button className="menu-toggle" type="button" aria-expanded={menuOpen} aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
      <nav className={menuOpen ? 'nav-links is-open' : 'nav-links'} aria-label="Primary navigation">{navItems.map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} onClick={closeMenu}><span>0{index + 1}</span>{item}</a>)}<a className="nav-github" href="https://github.com/Mr-Manish-Pal" target="_blank" rel="noreferrer" aria-label="Open GitHub profile"><Github size={16} /></a></nav>
    </header>
    <main>
      <section className="hero section-pad" id="home"><div className="hero-copy"><motion.div className="status-line" initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .55 }}><span className="status-dot" /> available for purposeful builds <span className="slash">//</span> meerut, in</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1, duration: .7 }}>Manish <em>Pal</em></motion.h1><motion.p className="hero-role" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .25 }}>Embedded Systems Engineer <span>|</span> ECE Student</motion.p><motion.p className="hero-intro" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .35 }}>Building practical embedded systems at the intersection of electronics, firmware, Linux, and edge AI.</motion.p><motion.div className="hero-actions" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .45 }}><a className="button button-primary" href="#projects">View projects <ArrowUpRight size={17} /></a><a className="button button-quiet" href="https://github.com/Mr-Manish-Pal" target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a><a className="resume-link" href="/resume/Manish_Pal_Resume.pdf" download>Download resume <MoveUpRight size={14} /></a></motion.div><div className="hero-tags" aria-label="Technical focus areas">{['ESP32', 'STM32', 'C/C++', 'Python', 'FreeRTOS', 'TinyML', 'Linux', 'PCB design'].map(tag => <span key={tag}>{tag}</span>)}</div></div><HeroDiagram /></section>
      <div className="ticker" aria-hidden="true"><div><span>HARDWARE</span><i>→</i><span>FIRMWARE</span><i>→</i><span>LINUX</span><i>→</i><span>EDGE AI</span><i>→</i><span>RESEARCH</span><i>→</i><span>HARDWARE</span><i>→</i><span>FIRMWARE</span><i>→</i><span>LINUX</span></div></div>
      <section className="section-pad about-section" id="about"><SectionHeading eyebrow="01 / context" title="Built close to the metal." text="A developing engineer who likes the moment a schematic becomes a signal, and a signal becomes something useful." /><div className="about-grid"><div className="about-body"><p>I’m a B.Tech Electronics & Communication Engineering student focused on the space where hardware and firmware meet. My work leans practical: wire the system, read the datasheet, measure the signal, then make the next iteration better.</p><p>Alongside embedded systems, I’m exploring Edge AI and TinyML, Linux-based development, and the research questions that shape efficient, secure computing.</p><div className="philosophy"><span>engineering philosophy</span><strong>Build. Debug.<br /><em>Measure. Optimize.</em></strong></div></div><div className="snapshot-grid">{['Embedded systems', 'Hardware debugging', 'Firmware development', 'Edge AI / TinyML', 'Linux development', 'PCB design', 'Research', 'Open source'].map((item, index) => { const Icon = iconMap[index]; return <div className="snapshot-card" key={item}><Icon size={18} /><span>{item}</span><small>0{index + 1}</small></div> })}</div></div></section>
      <section className="section-pad dark-band" id="skills"><SectionHeading eyebrow="02 / capability map" title="The engineering toolbox." text="A living skill matrix: working knowledge where I build, and clear labels where I’m still learning." /><div className="skill-grid">{skillGroups.map((group, index) => <motion.article className="skill-card" key={group.label} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ delay: index * .05 }}><div className="skill-card-top"><span>0{index + 1}</span><span className="skill-level">{group.level}</span></div><h3>{group.label}</h3><div className="chip-list">{group.items.map(item => <span key={item}>{item}</span>)}</div></motion.article>)}</div></section>
      <section className="section-pad projects-section" id="projects"><div className="section-heading heading-row"><div><span className="eyebrow"><Asterisk size={13} /> 03 / selected work</span><h2>Projects with a<br /><em>reason to exist.</em></h2></div><p>Hardware-led explorations, documented with the useful parts: the problem, the constraints, and what comes next.</p></div><div className="project-grid">{projects.map((project, index) => <ProjectCard key={project.id} project={project} featured={index === 0} onOpen={setSelectedProject} />)}</div></section>
      <section className="section-pad research-section" id="research"><SectionHeading eyebrow="04 / questions in progress" title="Research & technical interests" text="Not claims of publication. A map of the problems I want to understand more deeply." /><div className="research-list">{researchTopics.map(([topic, description, status], index) => <article className="research-row" key={topic}><span className="research-number">0{index + 1}</span><div className="research-icon"><Search size={18} /></div><div className="research-content"><h3>{topic}</h3><p>{description}</p></div><span className="research-status">{status}</span><ChevronRight size={17} /></article>)}</div></section>
      <section className="section-pad experience-section" id="experience"><div className="experience-grid"><div><SectionHeading eyebrow="05 / field notes" title="Experience that starts at the bench." /><div className="timeline"><div className="timeline-item"><span className="timeline-marker" /><div><span className="timeline-date">Hands-on electronics experience <i>~ 3.5 years</i></span><h3>Practical troubleshooting & repair</h3><p>Hands-on exposure to TV and audio amplifier systems, home theatre systems, dish antenna systems, PCB debugging, component-level troubleshooting, and electronic equipment diagnostics.</p></div></div><div className="timeline-item"><span className="timeline-marker muted" /><div><span className="timeline-date">Summer internship <i>dates / organization to be added</i></span><h3>Internship details pending</h3><p className="placeholder">[Add organization, dates, and scope when confirmed.]</p></div></div></div></div><div className="education-card"><span className="eyebrow"><BookOpen size={13} /> education</span><span className="education-status">currently pursuing</span><h3>B.Tech</h3><p>Electronics & Communication Engineering</p><strong>Dewan VS Group of Engineering & Technology</strong><span>Meerut, Uttar Pradesh</span></div></div></section>
      <section className="section-pad cert-section" id="certifications"><SectionHeading eyebrow="06 / credentials" title="Learning, documented." text="A small, honest record. Supporting details can be attached as they become available." /><div className="cert-grid">{['Basic Computer Certificate', 'Technofilia / TechnoFliia Certificate', 'School / college competition certificates'].map((title, index) => <article className="cert-card" key={title}><div className="cert-icon"><ShieldCheck size={18} /></div><span>0{index + 1} / certificate</span><h3>{title}</h3><p>Issuer: <b>[Add information]</b><br />Date: <b>[Add information]</b><br />Credential ID: <b>[Add information]</b></p></article>)}</div></section>
      <section className="section-pad toolbox-section"><div className="toolbox-header"><SectionHeading eyebrow="07 / bench inventory" title="Tools I reach for." /><span className="terminal-badge"><span className="status-dot" /> system.status = "building"</span></div><div className="toolbox-list">{toolbox.map((item, index) => <span key={item}><Box size={14} />{item}<small>0{index + 1}</small></span>)}</div></section>
      <section className="section-pad contact-section" id="contact"><div className="contact-copy"><SectionHeading eyebrow="08 / open channel" title={<>Let's build<br /><em>something.</em></>} text="Have a hardware problem, a firmware question, or a thoughtful collaboration in mind? The cleanest channel is GitHub." /><div className="contact-links"><a href="https://github.com/Mr-Manish-Pal" target="_blank" rel="noreferrer"><Github size={18} /> GitHub <ArrowUpRight size={15} /></a><span>LinkedIn <small>[Add profile]</small></span><span><Send size={18} /> Email <small>[Add email]</small></span></div></div><form className="contact-form" onSubmit={(event) => event.preventDefault()}><label>Name<input type="text" name="name" placeholder="Your name" /></label><label>Email<input type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea name="message" rows={4} placeholder="What are you building?" /></label><button className="button button-primary" type="submit">Send message <ArrowUpRight size={17} /></button><small>Frontend-only form. No backend or email service is configured.</small></form></section>
      <section className="resume-band"><div><span className="eyebrow"><Asterisk size={13} /> next artifact</span><h2>Want the complete technical profile?</h2></div><a className="button button-primary" href="/resume/Manish_Pal_Resume.pdf" download>Download resume <ArrowUpRight size={17} /></a></section>
    </main>
    <footer><a className="wordmark" href="#home"><span className="wordmark-mark">MP</span><span>MANISH PAL <small>/ EMBEDDED SYSTEMS</small></span></a><p>Embedded Systems Engineer <span>|</span> ECE</p><a href="https://github.com/Mr-Manish-Pal" target="_blank" rel="noreferrer"><Github size={16} /> github.com/Mr-Manish-Pal</a><small>© {new Date().getFullYear()} Manish Pal. Built with intent.</small></footer>
    <AnimatePresence>{selectedProject && <ProjectModal project={selectedProject} onClose={() => setSelectedProject(null)} />}</AnimatePresence>
  </div>
}

function HeroDiagram() { return <div className="hero-diagram" aria-label="Abstract embedded systems visualization"><div className="diagram-grid" /><div className="chip"><span>EDGE NODE</span><strong>IO</strong><small>SENSOR / BUS</small></div><div className="trace trace-one" /><div className="trace trace-two" /><div className="trace trace-three" /><div className="port port-one">UART</div><div className="port port-two">I2C</div><div className="port port-three">SPI</div><div className="wave"><span>signal / 01</span><svg viewBox="0 0 280 70" role="presentation"><path d="M0 44h24V18h23v37h20V28h22v16h24V12h22v43h25V34h24v10h23V23h22v21h25" /></svg></div><div className="diagram-label"><Terminal size={13} /> target = "embedded_systems"</div><div className="crosshair" /></div> }

function ProjectCard({ project, featured, onOpen }: { project: Project; featured?: boolean; onOpen: (project: Project) => void }) { return <motion.article className={`project-card ${featured ? 'featured-project' : ''}`} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .18 }} whileHover={{ y: -5 }} transition={{ duration: .35 }}><div className="project-card-top"><span className="project-label"><b>{project.number}</b><span>/ {project.category}</span></span><span className={`project-status ${project.status.toLowerCase().replace(' ', '-')}`}>{project.status}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="project-tags">{project.technologies.map(tag => <span key={tag}>[{tag}]</span>)}</div><div className="project-card-bottom"><button type="button" onClick={() => onOpen(project)}>View project <ArrowUpRight size={16} /></button>{project.github && <a href={project.github} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} GitHub repository`}><Github size={18} /></a>}</div>{featured && <div className="project-card-glow" />}</motion.article> }

function ProjectModal({ project, onClose }: { project: Project; onClose: () => void }) { return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.article className="project-modal" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 12 }} onClick={event => event.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="project-title"><button className="modal-close" type="button" onClick={onClose} aria-label="Close project details"><X size={19} /></button><span className="eyebrow"><Asterisk size={13} /> {project.number} / {project.category}</span><h2 id="project-title">{project.title}</h2><span className="modal-status">{project.status}</span><div className="modal-body"><div><h3>Problem</h3><p>{project.problem}</p><h3>Approach</h3><p>{project.approach}</p><h3>Future improvements</h3><p>{project.future}</p></div><div><h3>Hardware</h3><div className="modal-chips">{project.hardware.map(item => <span key={item}>{item}</span>)}</div><h3>Software</h3><div className="modal-chips">{project.software.map(item => <span key={item}>{item}</span>)}</div><h3>Challenges</h3><ul>{project.challenges.map(item => <li key={item}>{item}</li>)}</ul></div></div>{project.github && <a className="button button-primary" href={project.github} target="_blank" rel="noreferrer"><Github size={17} /> View repository</a>}</motion.article></motion.div> }

export default App
